[package]
name = "tms_service"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.22"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
html_scraper = { path = "../html_scraper" }
